# Generated by Django 4.1.3 on 2023-01-07 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_todo_options_usertodos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='users',
        ),
        migrations.AddField(
            model_name='todo',
            name='users',
            field=models.ManyToManyField(related_name='todos', through='main_app.UserTodos', to=settings.AUTH_USER_MODEL),
        ),
    ]
